caddy tls done with docs

diff --git a/meta/image/run b/meta/image/run
--- a/meta/image/run
+++ b/meta/image/run
@@ -9,5 +9,43 @@ fi
 DELIVERY_DOMAIN=$(echo "$DELIVERY_URL" | sed -E 's#https?://##' | sed 's#/##g')
 export DELIVERY_DOMAIN
 
+# Configure the app domain's Caddy address/TLS directives from TLS_MODE
+# auto:     Caddy manages a Let's Encrypt certificate automatically
+# manual:   TLS_CERT_FILE/TLS_KEY_FILE are used to serve TLS
+# external: TLS is terminated by a reverse proxy in front; the container only serves HTTP
+# disabled: no TLS at all, no https redirect
+TLS_MODE="${TLS_MODE:-auto}"
+
+case "$TLS_MODE" in
+    auto)
+        APP_ADDRESS="$DOMAIN_APP"
+        APP_TLS_DIRECTIVE=""
+        APP_REDIRECT_SNIPPET="noop"
+        ;;
+    manual)
+        APP_ADDRESS="$DOMAIN_APP"
+        APP_TLS_DIRECTIVE="tls $TLS_CERT_FILE $TLS_KEY_FILE"
+        APP_REDIRECT_SNIPPET="noop"
+        ;;
+    external)
+        APP_ADDRESS="$DOMAIN_APP:80"
+        APP_TLS_DIRECTIVE=""
+        APP_REDIRECT_SNIPPET="external_redirect"
+        ;;
+    disabled)
+        APP_ADDRESS="$DOMAIN_APP:80"
+        APP_TLS_DIRECTIVE=""
+        APP_REDIRECT_SNIPPET="noop"
+        ;;
+    *)
+        echo "Invalid TLS_MODE: $TLS_MODE. Must be one of: auto, external, manual, disabled." >&2
+        exit 1
+        ;;
+esac
+
+export APP_ADDRESS
+export APP_TLS_DIRECTIVE
+export APP_REDIRECT_SNIPPET
+
 # Run supervisor
 /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
